<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>cz.csb.fei.java2.lab01</groupId>
	<artifactId>lab01</artifactId>
	<version>1.0-SNAPSHOT</version>

	<packaging>jar</packaging>

	<name>lab01</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>25</maven.compiler.release>
		<JUnit.version>6.0.2</JUnit.version>
		<log4j.version>2.25.3</log4j.version>
		<lombok.version>1.18.42</lombok.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${JUnit.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>cz.vsb.fei.java2</groupId>
			<artifactId>lab01-text2asciiart</artifactId>
			<version>1.0.3</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.4</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.6.0</version>

				<configuration>
					<!--Set behavior of plugin, which archives should be created see
          https://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html-->
					<descriptorRefs>
						<!--Create FAT jar-->
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<!--Automatically create and add file MANIFEST.MF into jar and set specified properties-->
						<manifest>
							<mainClass>cz.vsb.fei.java2.lab01.App</mainClass>
						</manifest>
					</archive>
				</configuration>

				<executions>
					<!-- Setup that goal single should be automatically executed during phase package-->
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>



			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.8.1</version>
				<executions>
					<!-- Setup that goal copy-dependencies should be automatically executed during phase package-->
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<!--Specify where should be dependencies (libraries) copied-->
							<outputDirectory>${project.build.directory}/libs</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.2</version>
				<configuration>
					<archive>
						<!--Automatically create and add file MANIFEST.MF into jar and set specified additional properties-->
						<manifestEntries>
							<Name>cz/csb/fei/java2/lab01/App</Name>
							<Implementation-Build-Date>${maven.build.timestamp}</Implementation-Build-Date>
							<Implementation-Title>${project.groupId}.${project.artifactId}</Implementation-Title>
							<Implementation-Vendor>VŠB FEI Departmet of Computer Science</Implementation-Vendor>
							<Implementation-Version>${project.version}</Implementation-Version>
						</manifestEntries>
						<!--Automatically create and add file MANIFEST.MF into jar and set specified properties-->
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>libs/</classpathPrefix>
							<mainClass>cz.vsb.fei.java2.lab01.App</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>

			<plugin>
				<!--Plugin create customized version of JDK together with your application which can be
                distributed to any computer with same platform where you build this Jlink-->
				<artifactId>maven-jlink-plugin</artifactId>
				<version>3.2.0</version>
				<extensions>true</extensions>
				<executions>
					<!-- Setup that goal jlink should be automatically executed during phase package-->
					<execution>
						<id>create-jlink-image</id>
						<phase>package</phase>
						<goals>
							<goal>jlink</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!--Set classifier name to change suffix of generated file, otherwise module finish with error-->
					<classifier>jlink</classifier>
				</configuration>
			</plugin>


		</plugins>
	</build>

	<repositories>
		<repository>
			<id>vsb-education</id>
			<url>https://artifactory.cs.vsb.cz/repository/education-releases/</url>
		</repository>
	</repositories>

</project>
