package lab.map;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class MapRepository {

    private static Connection connection;

    private MapRepository() {}

    private static Connection getConnection() {
        if (connection == null) {
            try {
                connection = DriverManager.getConnection("jdbc:h2:file:./rhythm-game-db");
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        return connection;
    }

        public static void init() {

            try (Statement stm = getConnection().createStatement()) {

                stm.executeUpdate("CREATE TABLE IF NOT EXISTS rg_songs (song_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(100), difficulty VARCHAR(50), file_path VARCHAR(255), music_path VARCHAR(255), bpm INT, duration_seconds INT)");

                stm.executeUpdate("CREATE TABLE IF NOT EXISTS rg_scores (score_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, song_id INT, username VARCHAR(50), points INT)");

    

                if (isDbEmpty()) {

                    insertDefaults();

                }

            } catch (SQLException e) {

                e.printStackTrace();

            }

        }

    

        private static boolean isDbEmpty() throws SQLException {

            try (Statement stm = getConnection().createStatement();

                 ResultSet rs = stm.executeQuery("SELECT COUNT(*) FROM rg_songs")) {

                if (rs.next()) {

                    return rs.getInt(1) == 0;

                }

            }

            return true;

        }

    

        private static void insertDefaults() throws SQLException {

            String sql = "INSERT INTO rg_songs (title, difficulty, file_path, music_path, bpm, duration_seconds) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement ps = getConnection().prepareStatement(sql)) {

                addSongBatch(ps, "Big City Life", "/musicFiles/Big City Life - Luude, Mattafix.mp3", 87, 147);

                addSongBatch(ps, "Down Under", "/musicFiles/Down Under - Luude, Colin Hay.mp3", 172, 159);

                addSongBatch(ps, "FOREVER AGAIN", "/musicFiles/FOREVER AGAIN - Yeat.mp3", 125, 200);

                addSongBatch(ps, "Kills", "/musicFiles/Kills - Chief Keef.mp3", 150, 170);

                addSongBatch(ps, "silicon wings", "/musicFiles/silicon wings - Yung Lean.mp3", 160, 136);

                ps.executeBatch();

            }

        }

    

        private static void addSongBatch(PreparedStatement ps, String title, String path, int bpm, int duration) throws SQLException {

            String[] diffs = {"Lehká", "Střední", "Těžká", "Expert"};

            for (String d : diffs) {

                ps.setString(1, title);

                ps.setString(2, d);

                ps.setString(3, "maps/gen.txt"); // Placeholder

                ps.setString(4, path);

                ps.setInt(5, bpm);

                ps.setInt(6, duration);

                ps.addBatch();

            }

        }

    

        public static List<MapInfo> load() throws MapException {

            init();

            List<MapInfo> result = new ArrayList<>();

            try (Statement stm = getConnection().createStatement();

                 ResultSet rs = stm.executeQuery("SELECT * FROM rg_songs")) {

                while (rs.next()) {

                    MapInfo map = new MapInfo(

                        rs.getLong("song_id"), 

                        rs.getString("title"), 

                        rs.getString("difficulty"), 

                        rs.getString("file_path"),

                        rs.getString("music_path"),

                        rs.getInt("bpm"),

                        rs.getInt("duration_seconds")

                    );

                    map.setHighScore(loadHighScore(map.getId()));

                    result.add(map);

                }

            }

            catch (SQLException e) {

                throw new MapException("Error loading maps", e);

            }

            return result;

        }

    private static Score loadHighScore(long songId) throws SQLException {
        String sql = "SELECT username, points FROM rg_scores WHERE song_id = ? ORDER BY points DESC LIMIT 1";
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setLong(1, songId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new Score(rs.getInt("points"), rs.getString("username"));
                }
            }
        }
        return new Score(0, "---");
    }

    public static void saveScore(long songId, String name, int points) throws MapException {
        String sql = "INSERT INTO rg_scores (song_id, username, points) VALUES (?, ?, ?)";
        try (PreparedStatement ps = getConnection().prepareStatement(sql)) {
            ps.setLong(1, songId);
            ps.setString(2, name);
            ps.setInt(3, points);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new MapException("Error saving score", e);
        }
    }



    private static org.h2.tools.Server server;

    public static void startDBWebServer() {
        try {
            server = org.h2.tools.Server.createWebServer().start();
            System.out.println("H2 Console URL: " + server.getURL());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void stopDBWebServer() {
        if (server != null) {
            server.stop();
        }
    }
}
