drop table tds_historical_data cascade constraints;
drop table tds_comments cascade constraints;
drop table tds_user_achievements cascade constraints;
drop table tds_achievements cascade constraints;
drop table tds_game_sessions cascade constraints;
drop table tds_song_variants cascade constraints;
drop table tds_songs cascade constraints;
drop table tds_admins cascade constraints;
drop table tds_players cascade constraints;
drop table tds_users cascade constraints;

-- 1. SUPERTYP: Spolecna data pro vsechny uzivatele
create table tds_users (
   user_id       number generated by default as identity,
   username      varchar2(50) not null,
   email         varchar2(100) not null,
   password_hash varchar2(255) not null,
   role          char(1) default 'P' not null,
   created_at    timestamp default current_timestamp not null,
   constraint pk_tds_users primary key ( user_id ),
   constraint uq_tds_users_username unique ( username ),
   constraint uq_tds_users_email unique ( email ),
   constraint chk_tds_users_role check ( role in ( 'P',
                                                   'A' ) )
);

-- 2. SUBTYP 1: Hráči
create table tds_players (
   user_id      number,
   display_name varchar2(50) not null,
   total_points number default 0 not null,
   level_number number default 1 not null,
   constraint pk_tds_players primary key ( user_id ),
   constraint fk_tds_players_users foreign key ( user_id )
      references tds_users ( user_id )
         on delete cascade,
   constraint chk_tds_players_points check ( total_points >= 0 )
);

-- 3. SUBTYP 2: Administrátoři
create table tds_admins (
   user_id     number,
   admin_level number default 1 not null,
   constraint pk_tds_admins primary key ( user_id ),
   constraint fk_tds_admins_users foreign key ( user_id )
      references tds_users ( user_id )
         on delete cascade,
   constraint chk_tds_admins_level check ( admin_level between 1 and 5 )
);

-- 4. Skladby
create table tds_songs (
   song_id          number generated by default as identity,
   title            varchar2(100) not null,
   artist           varchar2(100) not null,
   bpm              number(5,2),
   duration_seconds number,
   cover_image      blob,
   constraint pk_tds_songs primary key ( song_id ),
   constraint chk_tds_songs_bpm check ( bpm > 0 )
);

-- 5. Varianty skladeb
create table tds_song_variants (
   variant_id      number generated by default as identity,
   song_id         number not null,
   difficulty_name varchar2(20) not null,
   note_count      number not null,
   max_score       number not null,
   constraint pk_tds_song_variants primary key ( variant_id ),
   constraint fk_variants_tds_songs foreign key ( song_id )
      references tds_songs ( song_id )
         on delete cascade,
   constraint chk_variants_tds_notes check ( note_count > 0 )
);

-- 6. Herní sezení
create table tds_game_sessions (
   session_id number generated by default as identity,
   user_id    number not null,
   variant_id number not null,
   score      number not null,
   accuracy   number(5,2),
   max_combo  number,
   played_at  timestamp default current_timestamp not null,
   constraint pk_tds_game_sessions primary key ( session_id ),
   constraint fk_sessions_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_sessions_tds_variants foreign key ( variant_id )
      references tds_song_variants ( variant_id )
         on delete cascade,
   constraint chk_tds_sessions_acc check ( accuracy between 0 and 100 )
);

-- 7. Achievementy
create table tds_achievements (
   achievement_id  number generated by default as identity,
   title           varchar2(50) not null,
   description     clob,
   required_points number,
   constraint pk_tds_achievements primary key ( achievement_id ),
   constraint uq_tds_achievements_title unique ( title )
);

-- 8. Získané achievementy
create table tds_user_achievements (
   user_id        number not null,
   achievement_id number not null,
   earned_at      timestamp default current_timestamp not null,
   constraint pk_tds_user_achievements primary key ( user_id,
                                                     achievement_id ),
   constraint fk_user_ach_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_user_ach_tds_ach foreign key ( achievement_id )
      references tds_achievements ( achievement_id )
         on delete cascade
);

-- 9. Komentáře pod skladbou 
create table tds_comments (
   comment_id        number generated by default as identity,
   user_id           number not null,
   song_id           number not null,
   parent_comment_id number,
   comment_text      varchar2(500) not null,
   created_at        timestamp default current_timestamp not null,
   constraint pk_tds_comments primary key ( comment_id ),
   constraint fk_comments_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_comments_tds_songs foreign key ( song_id )
      references tds_songs ( song_id )
         on delete cascade,
   constraint fk_comments_tds_parent foreign key ( parent_comment_id )
      references tds_comments ( comment_id )
         on delete cascade
);

-- 10. Historická data 
create table tds_historical_data (
   record_id      number generated by default as identity,
   table_name     varchar2(50) not null,
   record_fk_id   number not null,
   attribute_name varchar2(50) not null,
   old_value      varchar2(255),
   new_value      varchar2(255),
   changed_at     timestamp default current_timestamp not null,
   constraint pk_tds_historical_data primary key ( record_id )
);