   SET DEFINE OFF;
alter session set nls_date_language = english;

/* ============================================================================
   TDS I - Rhythm game database

   ============================================================================ */

begin
   execute immediate 'DROP SYNONYM syn_tds_top_players';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP VIEW v_tds_top_players';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP VIEW v_tds_high_scores';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP VIEW v_tds_player_summary';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP SEQUENCE seq_tds_custom';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_archived_sessions CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_datatypes CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_alter CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_alter_renamed CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_objects CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_player_copy CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_constraints CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_child CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_demo_parent CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_content_reports CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_historical_data CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_comments CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_user_achievements CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_achievements CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_game_sessions CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_song_variants CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_songs CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_admins CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_players CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

begin
   execute immediate 'DROP TABLE tds_users CASCADE CONSTRAINTS PURGE';
exception
   when others then
      null;
end;
/

/* ============================================================================
   DDL - PROJECT TABLES
   ============================================================================ */

create table tds_users (
   user_id       number generated by default as identity,
   username      varchar2(50) not null,
   email         varchar2(100) not null,
   password_hash varchar2(255) not null,
   role          char(1) default 'P' not null,
   created_at    timestamp default current_timestamp not null,
   constraint pk_tds_users primary key ( user_id ),
   constraint uq_tds_users_username unique ( username ),
   constraint uq_tds_users_email unique ( email ),
   constraint chk_tds_users_role check ( role in ( 'P',
                                                   'A' ) )
);

create table tds_players (
   user_id      number,
   display_name varchar2(50) not null,
   total_points number default 0 not null,
   level_number number default 1 not null,
   constraint pk_tds_players primary key ( user_id ),
   constraint fk_tds_players_users foreign key ( user_id )
      references tds_users ( user_id )
         on delete cascade,
   constraint chk_tds_players_points check ( total_points >= 0 ),
   constraint chk_tds_players_level check ( level_number >= 1 )
);

create table tds_admins (
   user_id     number,
   admin_level number default 1 not null,
   constraint pk_tds_admins primary key ( user_id ),
   constraint fk_tds_admins_users foreign key ( user_id )
      references tds_users ( user_id )
         on delete cascade,
   constraint chk_tds_admins_level check ( admin_level between 1 and 5 )
);

create table tds_songs (
   song_id          number generated by default as identity,
   title            varchar2(100) not null,
   artist           varchar2(100) not null,
   bpm              number(5,2) not null,
   duration_seconds number not null,
   release_date     date,
   cover_image      blob,
   constraint pk_tds_songs primary key ( song_id ),
   constraint uq_tds_songs_title_artist unique ( title,
                                                 artist ),
   constraint chk_tds_songs_bpm check ( bpm > 0 ),
   constraint chk_tds_songs_duration check ( duration_seconds > 0 )
);

create table tds_song_variants (
   variant_id      number generated by default as identity,
   song_id         number not null,
   difficulty_name varchar2(20) not null,
   note_count      number not null,
   max_score       number not null,
   constraint pk_tds_song_variants primary key ( variant_id ),
   constraint fk_variants_tds_songs foreign key ( song_id )
      references tds_songs ( song_id )
         on delete cascade,
   constraint uq_tds_variants_song_diff unique ( song_id,
                                                 difficulty_name ),
   constraint chk_variants_tds_notes check ( note_count > 0 ),
   constraint chk_variants_tds_score check ( max_score > 0 )
);

create table tds_game_sessions (
   session_id number generated by default as identity,
   user_id    number not null,
   variant_id number not null,
   score      number not null,
   accuracy   number(5,2),
   max_combo  number,
   played_at  timestamp default current_timestamp not null,
   constraint pk_tds_game_sessions primary key ( session_id ),
   constraint fk_sessions_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_sessions_tds_variants foreign key ( variant_id )
      references tds_song_variants ( variant_id )
         on delete cascade,
   constraint chk_tds_sessions_score check ( score >= 0 ),
   constraint chk_tds_sessions_acc check ( accuracy between 0 and 100 ),
   constraint chk_tds_sessions_combo
      check ( max_combo is null
          or max_combo >= 0 )
);

create table tds_achievements (
   achievement_id  number generated by default as identity,
   title           varchar2(50) not null,
   description     clob,
   required_points number default 0 not null,
   constraint pk_tds_achievements primary key ( achievement_id ),
   constraint uq_tds_achievements_title unique ( title ),
   constraint chk_tds_achievements_points check ( required_points >= 0 )
);

-- Identifying 1:N relationships:
-- tds_players -> tds_user_achievements and
-- tds_achievements -> tds_user_achievements.
-- The transferred foreign keys are also parts of the primary key.
create table tds_user_achievements (
   user_id        number not null,
   achievement_id number not null,
   constraint pk_tds_user_achievements primary key ( user_id,
                                                     achievement_id ),
   constraint fk_user_ach_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_user_ach_tds_ach foreign key ( achievement_id )
      references tds_achievements ( achievement_id )
         on delete cascade
);

create table tds_comments (
   comment_id        number generated by default as identity,
   user_id           number not null,
   song_id           number not null,
   parent_comment_id number,
   comment_text      varchar2(500) not null,
   created_at        timestamp default current_timestamp not null,
   constraint pk_tds_comments primary key ( comment_id ),
   constraint fk_comments_tds_players foreign key ( user_id )
      references tds_players ( user_id )
         on delete cascade,
   constraint fk_comments_tds_songs foreign key ( song_id )
      references tds_songs ( song_id )
         on delete cascade,
   constraint fk_comments_tds_parent foreign key ( parent_comment_id )
      references tds_comments ( comment_id )
         on delete cascade
);

-- ARC example: one report points either to a song or to a comment, never both.
create table tds_content_reports (
   report_id  number generated by default as identity,
   song_id    number,
   comment_id number,
   reason     varchar2(255) not null,
   created_at timestamp default current_timestamp not null,
   constraint pk_tds_content_reports primary key ( report_id ),
   constraint fk_reports_song foreign key ( song_id )
      references tds_songs ( song_id ),
   constraint fk_reports_comment foreign key ( comment_id )
      references tds_comments ( comment_id ),
   constraint chk_reports_arc
      check ( ( song_id is not null
         and comment_id is null )
          or ( song_id is null
         and comment_id is not null ) )
);

create table tds_historical_data (
   record_id      number generated by default as identity,
   table_name     varchar2(50) not null,
   record_fk_id   number not null,
   attribute_name varchar2(50) not null,
   old_value      varchar2(255),
   new_value      varchar2(255),
   changed_at     timestamp default current_timestamp not null,
   constraint pk_tds_historical_data primary key ( record_id )
);

create or replace trigger trg_tds_users_history before
   update of email,username,role on tds_users
   for each row
begin
   if nvl(
      :old.email,
      '#'
   ) != nvl(
      :new.email,
      '#'
   ) then
      insert into tds_historical_data (
         table_name,
         record_fk_id,
         attribute_name,
         old_value,
         new_value
      ) values ( 'TDS_USERS',
                 :old.user_id,
                 'EMAIL',
                 :old.email,
                 :new.email );
   end if;

   if nvl(
      :old.username,
      '#'
   ) != nvl(
      :new.username,
      '#'
   ) then
      insert into tds_historical_data (
         table_name,
         record_fk_id,
         attribute_name,
         old_value,
         new_value
      ) values ( 'TDS_USERS',
                 :old.user_id,
                 'USERNAME',
                 :old.username,
                 :new.username );
   end if;

   if nvl(
      :old.role,
      '#'
   ) != nvl(
      :new.role,
      '#'
   ) then
      insert into tds_historical_data (
         table_name,
         record_fk_id,
         attribute_name,
         old_value,
         new_value
      ) values ( 'TDS_USERS',
                 :old.user_id,
                 'ROLE',
                 :old.role,
                 :new.role );
   end if;
end;
/

/* ============================================================================
   DML - TEST DATA
   ============================================================================ */

insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 1,
           'RhythmGod',
           'god@rhythm.cz',
           'hash1',
           'P',
           timestamp '2024-01-10 10:00:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 2,
           'NoobMaster',
           'noob@rhythm.cz',
           'hash2',
           'P',
           timestamp '2024-02-15 11:30:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 3,
           'AdminJoe',
           'admin@rhythm.cz',
           'hash3',
           'A',
           timestamp '2024-03-01 08:15:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 4,
           'ComboQueen',
           'combo.queen@rhythm.cz',
           'hash4',
           'P',
           timestamp '2024-04-05 14:20:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 5,
           'SilentBeat',
           'silentbeat@example.com',
           'hash5',
           'P',
           timestamp '2024-05-12 19:45:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 6,
           'ChartAdmin',
           'chart.admin@rhythm.cz',
           'hash6',
           'A',
           timestamp '2024-06-22 09:10:00' );
insert into tds_users (
   user_id,
   username,
   email,
   password_hash,
   role,
   created_at
) values ( 7,
           'LateStarter',
           'late_starter@rhythm.cz',
           'hash7',
           'P',
           timestamp '2024-07-18 21:00:00' );

insert into tds_players (
   user_id,
   display_name,
   total_points,
   level_number
) values ( 1,
           'God Mode',
           50000,
           42 );
insert into tds_players (
   user_id,
   display_name,
   total_points,
   level_number
) values ( 2,
           'Noobie',
           1500,
           5 );
insert into tds_players (
   user_id,
   display_name,
   total_points,
   level_number
) values ( 4,
           'Combo Queen',
           27000,
           26 );
insert into tds_players (
   user_id,
   display_name,
   total_points,
   level_number
) values ( 5,
           'Silent Beat',
           0,
           1 );
insert into tds_players (
   user_id,
   display_name,
   total_points,
   level_number
) values ( 7,
           'Late Starter',
           600,
           2 );

insert into tds_admins (
   user_id,
   admin_level
) values ( 3,
           5 );
insert into tds_admins (
   user_id,
   admin_level
) values ( 6,
           3 );

insert into tds_songs (
   song_id,
   title,
   artist,
   bpm,
   duration_seconds,
   release_date,
   cover_image
) values ( 1,
           'Starlight',
           'Muse',
           122,
           240,
           date '2006-09-04',
           empty_blob() );
insert into tds_songs (
   song_id,
   title,
   artist,
   bpm,
   duration_seconds,
   release_date,
   cover_image
) values ( 2,
           'Through the Fire',
           'DragonForce',
           200,
           442,
           date '2006-01-01',
           empty_blob() );
insert into tds_songs (
   song_id,
   title,
   artist,
   bpm,
   duration_seconds,
   release_date,
   cover_image
) values ( 3,
           'Crystal Pulse',
           'Neon Arcade',
           168,
           195,
           date '2022-05-12',
           empty_blob() );
insert into tds_songs (
   song_id,
   title,
   artist,
   bpm,
   duration_seconds,
   release_date,
   cover_image
) values ( 4,
           'Quiet Intro',
           'Lo-Fi Lab',
           88,
           130,
           date '2021-11-20',
           empty_blob() );
insert into tds_songs (
   song_id,
   title,
   artist,
   bpm,
   duration_seconds,
   release_date,
   cover_image
) values ( 5,
           'Final Velocity',
           'Synth Runner',
           175,
           210,
           date '2023-03-09',
           empty_blob() );

insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 1,
           1,
           'Easy',
           200,
           20000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 2,
           1,
           'Hard',
           500,
           50000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 3,
           2,
           'Extreme',
           2500,
           250000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 4,
           3,
           'Normal',
           420,
           42000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 5,
           3,
           'Hard',
           980,
           98000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 6,
           4,
           'Easy',
           120,
           12000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 7,
           5,
           'Hard',
           1050,
           105000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 8,
           5,
           'Expert',
           1600,
           160000 );
insert into tds_song_variants (
   variant_id,
   song_id,
   difficulty_name,
   note_count,
   max_score
) values ( 9,
           2,
           'Hard',
           1200,
           120000 );

insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 1,
           1,
           3,
           245000,
           98.50,
           2400,
           timestamp '2024-09-01 20:10:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 2,
           2,
           1,
           15000,
           85.00,
           150,
           timestamp '2024-09-02 18:30:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 3,
           4,
           8,
           154000,
           96.25,
           1490,
           timestamp '2024-09-03 21:45:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 4,
           1,
           2,
           48000,
           99.10,
           500,
           timestamp '2024-09-04 22:00:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 5,
           7,
           6,
           8000,
           72.40,
           null,
           timestamp '2024-09-05 12:15:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 6,
           4,
           5,
           90000,
           93.80,
           920,
           timestamp '2024-09-06 13:40:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 7,
           2,
           4,
           39000,
           88.20,
           370,
           timestamp '2024-09-07 15:05:00' );
insert into tds_game_sessions (
   session_id,
   user_id,
   variant_id,
   score,
   accuracy,
   max_combo,
   played_at
) values ( 8,
           1,
           8,
           160000,
           100.00,
           1600,
           timestamp '2024-09-08 23:59:00' );

insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 1,
           'First Steps',
           'Play your first song.',
           0 );
insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 2,
           'Godlike',
           'Get over 98 percent accuracy on Extreme.',
           10000 );
insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 3,
           'Combo Builder',
           'Reach a combo over 500.',
           5000 );
insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 4,
           'Perfect Run',
           'Reach 100 percent accuracy.',
           25000 );
insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 5,
           'Speed Reader',
           'Play a song above 170 BPM.',
           8000 );
insert into tds_achievements (
   achievement_id,
   title,
   description,
   required_points
) values ( 6,
           'Long Road',
           'Play at least five songs.',
           12000 );

insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 1,
           1 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 1,
           2 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 1,
           3 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 1,
           4 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 2,
           1 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 4,
           1 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 4,
           3 );
insert into tds_user_achievements (
   user_id,
   achievement_id
) values ( 7,
           1 );

insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 1,
           1,
           2,
           null,
           'This song is too fast!',
           timestamp '2024-09-09 10:00:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 2,
           2,
           2,
           1,
           'I agree, my fingers hurt.',
           timestamp '2024-09-09 10:05:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 3,
           4,
           2,
           1,
           'Practice the intro slowly first.',
           timestamp '2024-09-09 10:10:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 4,
           7,
           3,
           null,
           'Crystal Pulse has a nice rhythm.',
           timestamp '2024-09-10 09:00:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 5,
           1,
           3,
           4,
           'The hard chart is great for warmup.',
           timestamp '2024-09-10 09:30:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 6,
           4,
           5,
           null,
           'Final Velocity feels fair but intense.',
           timestamp '2024-09-11 16:00:00' );
insert into tds_comments (
   comment_id,
   user_id,
   song_id,
   parent_comment_id,
   comment_text,
   created_at
) values ( 7,
           2,
           5,
           6,
           'The last section is brutal.',
           timestamp '2024-09-11 16:15:00' );

insert into tds_content_reports (
   report_id,
   song_id,
   comment_id,
   reason,
   created_at
) values ( 1,
           2,
           null,
           'Song difficulty metadata should be reviewed.',
           timestamp '2024-09-12 08:00:00' );
insert into tds_content_reports (
   report_id,
   song_id,
   comment_id,
   reason,
   created_at
) values ( 2,
           null,
           7,
           'Comment contains subjective difficulty complaint.',
           timestamp '2024-09-12 08:05:00' );

-- Trigger demonstration for historical data and journaling.
update tds_users
   set
   email = 'rhythmgod@rhythm.cz'
 where user_id = 1;

commit;
