package lab.map;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.h2.tools.Server;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class MapRepository {

    private static final Logger log = LogManager.getLogger(MapRepository.class);
    private static Connection connection;

    private MapRepository() {
    }

    private static Connection getConnection() {
        if (connection == null) {
            try {
                connection = DriverManager.getConnection("jdbc:h2:file:./rhythm-game-db");
                log.debug("Database connection established.");
            } catch (SQLException e) {
                log.fatal("Could not connect to database", e);
                throw new RuntimeException(e);
            }
        }
        return connection;
    }

    public static void init() {
        try (Statement statement = getConnection().createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS rg_songs (
                        song_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(100),
                        difficulty VARCHAR(50),
                        file_path VARCHAR(255),
                        music_path VARCHAR(255),
                        bpm INT,
                        duration_seconds INT
                    )""");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS rg_scores (
                        score_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        song_id INT,
                        username VARCHAR(50),
                        points INT
                    )"""); // text block

            if (isDbEmpty()) {
                insertDefaults();
            }
        } catch (SQLException e) {
            log.warn("Table already exists. (asi)", e);
        }
    }

    private static boolean isDbEmpty() throws SQLException {
        try (Statement statement = getConnection().createStatement();
                ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM rg_songs")) {
            if (result.next()) {
                return result.getInt(1) == 0;
            }
        }
        return true;
    }

    private static void insertDefaults() throws SQLException {
        String sql = "INSERT INTO rg_songs (title, difficulty, file_path, music_path, bpm, duration_seconds) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(sql)) {
            addSongBatch(preparedStatement, "Big City Life", "/musicFiles/Big City Life - Luude, Mattafix.mp3", 87,
                    147);
            addSongBatch(preparedStatement, "silicon wings", "/musicFiles/silicon wings - Yung Lean.mp3", 160, 136);
            preparedStatement.executeBatch();
        }
    }

    private static void addSongBatch(PreparedStatement preparedStatement, String title, String path, int bpm,
            int duration) throws SQLException {
        String[] diffs = { "Lehká", "Střední", "Těžká", "Expert" };
        for (String d : diffs) {
            preparedStatement.setString(1, title);
            preparedStatement.setString(2, d);
            preparedStatement.setString(3, "maps/gen.txt");
            preparedStatement.setString(4, path);
            preparedStatement.setInt(5, bpm);
            preparedStatement.setInt(6, duration);
            preparedStatement.addBatch();
        }
    }

    public static List<MapInfo> load() throws MapException {
        init();
        List<MapInfo> result = new ArrayList<>();
        try (Statement statement = getConnection().createStatement();
                ResultSet resultSet = statement.executeQuery("SELECT * FROM rg_songs")) {
            while (resultSet.next()) {
                MapInfo map = new MapInfo(
                        resultSet.getLong("song_id"),
                        resultSet.getString("title"),
                        resultSet.getString("difficulty"),
                        resultSet.getString("file_path"),
                        resultSet.getString("music_path"),
                        resultSet.getInt("bpm"),
                        resultSet.getInt("duration_seconds"));
                map.setHighScore(loadHighScore(map.getId()));
                result.add(map);
            }
        } catch (SQLException e) {
            log.error("Error loading maps", e);
            throw new MapException("Error loading maps", e);
        }
        return result;
    }

    private static Score loadHighScore(long songId) throws SQLException {
        String sql = "SELECT username, points FROM rg_scores WHERE song_id = ? ORDER BY points DESC LIMIT 1";
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(sql)) {
            preparedStatement.setLong(1, songId);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    return new Score(resultSet.getInt("points"), resultSet.getString("username"));
                }
            }
        }
        return new Score(0, "---");
    }

    public static void saveScore(long songId, String name, int points) throws MapException {
        String sql = "INSERT INTO rg_scores (song_id, username, points) VALUES (?, ?, ?)";
        try (PreparedStatement preparedStatement = getConnection().prepareStatement(sql)) {
            preparedStatement.setLong(1, songId);
            preparedStatement.setString(2, name);
            preparedStatement.setInt(3, points);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            log.error("Error saving score", e);
            throw new MapException("Error saving score", e);
        }
    }

    private static Server server;

    public static void startDBWebServer() {
        // Start HTTP server for access H2 DB for look inside
        Path h2ServerProperties = Paths.get(System.getProperty("user.home"), ".h2.server.properties");
        try {
            Files.writeString(h2ServerProperties,
                    "0=Generic H2 (Embedded)|org.h2.Driver|jdbc\\:h2\\:file\\:./rhythm-game-db|",
                    StandardOpenOption.CREATE_NEW);
        } catch (IOException e) {
            log.warn("File {} probably exists.", h2ServerProperties, e);
        }
        stopDBWebServer();
        try {
            server = Server.createWebServer();
            log.info("DB Web server URL: {}", server.getURL());
            server.start();
            log.info("DB Web server started!");
        } catch (SQLException e) {
            log.error("Cannot create DB web server.", e);
        }
    }

    public static void stopDBWebServer() {
        // Stop HTTP server for access H2 DB
        if (server != null) {
            log.info("Ending DB web server BYE.");
            server.stop();
        }
    }
}
